### ISSUE TITLE
can not install v4.0.0

### ISSUE THREAD

**Issue by shikelong** [nanjingboy/nvmw#6]
node v4.0.0 download failed.

**Comment by Fonz001** [comment]
Same for v4.1.0

**Comment by SteveALee** [comment]
+1 for both versions

**Comment by java-4ever** [comment]
Same for v4.1.1.
The url has changed from https://nodejs.org/dist/v4.1.1/x64/node.exe to https://nodejs.org/dist/v4.1.1/node-v4.1.1-x64.msi

**Comment by nanjingboy** [comment]
please upgrade to the newest version
